--- # main task list for GlusterCluster

- apt_repository:
    repo: 'ppa:gluster/glusterfs-3.8'
    state: present
    update_cache: yes


- name: Install glusterfs-server
  apt:
    name: glusterfs-server
    state: latest

- name: Install xfsprogs
  apt:
    name : xfsprogs
    state: latest


- filesystem: 
    fstype: xfs
    dev: /dev/xvdb1


- name: Mount second volume, even after boot
  mount:
    path: /mnt/xvdb1
    src: /dev/xvdb1
    fstype: xfs
    state: mounted

- file:
    path: /mnt/xvdb1/brick
    state: directory
      
