--- #test playbook to attempt to mount the cluster

- hosts: tag_Gluster_Cluster
  become: yes
  become_method: sudo
  gather_facts: true
  tasks: 
  - name: Create Gluster Cluster
    gluster_volume:
      state: present
#      start_on_create: yes
      name: test1
      bricks: "/export/xvdb1/brick1"
      cluster: 
        - " {{ ansible_play_batch[0] }}"
        - " {{ ansible_play_batch[1] }}"
      replicas: 2
      force: true
    run_once: yes
    ignore_errors: yes