--- # This is the master playbook, to be called to demonstrate successful project


#Instance deployment/verification
- hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  gather_facts: true 
  roles:
  - InstanceDeploy

- hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - pause:
        seconds: 30
        prompt: allowing time to poll AWS
    - meta: refresh_inventory

#Configure instances for Cluster
- hosts: tag_Gluster_Cluster
  become: yes
  become_method: sudo
  gather_facts: true 
  roles:
  - GlusterCluster

#Configure Gluster Clients
#- hosts: tag_Gluster_Client
#  become: yes
#  become_method: sudo
#  gather_facts: true
#  vars:
#    glusterServer: "{{ groups['tag_Gluster_Cluster'] }}"
#  roles:
#  - GlusterClient