--- # This is the master playbook, to be called to demonstrate successful project

#define and format environmental variables
#- hosts: localhost
#  connection: local
#  become: yes
#  become_method: sudo
#  gather_facts: true
#  vars:
#    put various environmental variables here
#
#
#  tasks:
#    here is where to put all the tasks to save these variables
#    - name: 

# Begin Server deployment/verification
- hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  gather_facts: true

  roles:
    - InstanceDeploy

