--- # This is the master playbook, to be called to demonstrate successful project

#define and format environmental variables
#- hosts: localhost
#  connection: local
#  become: yes
#  become_method: sudo
#  gather_facts: true
#  vars:
#    put various environmental variables here
#
#
#  tasks:
#    here is where to put all the tasks to save these variables
#    - name: 

#Instance deployment/verification
- hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  gather_facts: true 
  roles:
  - InstanceDeploy


- wait_for:
  host: tag_Gluster_Cluster[0]


#Configure instances for Cluster
- hosts: tag_Gluster_Cluster
  become: yes
  become_method: sudo
  gather_facts: true 
  roles:
  - GlusterCluster


#testing out a new thing
#- hosts: tag_Gluster_Cluster[0]
#  become: yes
#  become_method: sudo
#  gather_facts: true
#  tasks:
#    - file:
#        path: /export/xvdb1/brick/nope
#        state: directory
