--- #test file for GlusterClient config;
#run this when servers already deployed, and volumes already running


#Configure Gluster Clients
- hosts: tag_Gluster_Client
  become: yes
  become_method: sudo
  gather_facts: true
  vars:
    fruits:
      - apple
      - banana
      - cake
    glusterServer:
      - { for host in groups['tag_Gluster_Cluster'] }
            {{hostvars[host]["ec2_private_ip_address"] }}
        { endfor }
  roles:
  - GlusterClient