--- # main task list for configuring Gluster Clients

- modprobe:
    name: fuse
    state: present

- apt_repository:
    repo: 'ppa:gluster/glusterfs-3.8'
    state: present
    update_cache: yes

- name: Install glusterfs-client
  apt:
    name: glusterfs-client
    state: latest

- file:
    path: /mnt/gluster
    state: directory

- debug:
    var: fruits

- debug:
    var: fruits [1]

- debug:
    var: glusterServer

#- name: Mount Gluster Volume
#  mount:
#    name: /mnt/gluster
#    src: "{{ glusterServer[0] }}:/gv0"
#    fstype: glusterfs
#    state: mounted
#    opts: backupvolfile-server="{{ glusterServer[1] }}"