--- # main task list for InstanceDeploy



- name: Provision Gluster Cluster in first subnet
  ec2:
    key_name: "{{ AWSkey_name }}"
    group_id: "{{ AWSgroup_id }}"
    instance_type: t2.micro
    assign_public_ip: yes
    image: "{{ AWSimage_id }}"
    volumes: 
      - device_name: /dev/sdb
        delete_on_termination: true
        volume_type: gp2
        volume_size: 2
        snapshot: snap-04adac52ef92895ad
    region: "{{ AWSregion }}"
#    zone: "{{ AWSzone }} "
    vpc_subnet_id: "{{ AWSvpc_subnet_id[0] }}"
    wait: true
    exact_count: 1
    count_tag:
      Gluster: Cluster
      Subnet: "{{ AWSvpc_subnet_id[0] }}"
    instance_tags:
      Gluster: Cluster
      Subnet: "{{ AWSvpc_subnet_id[0] }}"
      Name: GlusterCluster

- name: Provision Gluster Cluster in second subnet
  ec2:
    key_name: "{{ AWSkey_name }}"
    group_id: "{{ AWSgroup_id }}"
    instance_type: t2.micro
    assign_public_ip: yes
    image: "{{ AWSimage_id }}"
    volumes: 
      - device_name: /dev/sdb
        delete_on_termination: true
        volume_type: gp2
        volume_size: 2
        snapshot: snap-04adac52ef92895ad
    region: "{{ AWSregion }}"
#    zone: "{{ AWSzone }} "
    vpc_subnet_id: "{{ AWSvpc_subnet_id[1] }}"
    wait: true
    exact_count: 1
    count_tag:
      Gluster: Cluster
      Subnet: "{{ AWSvpc_subnet_id[1] }}"
    instance_tags:
      Gluster: Cluster
      Subnet: "{{ AWSvpc_subnet_id[1] }}"
      Name: GlusterCluster




- name: Provision Gluster Client in first subnet
  ec2:
    key_name: "{{ AWSkey_name }}"
    group_id: "{{ AWSgroup_id }}"
    instance_type: t2.micro
    assign_public_ip: yes
    image: "{{ AWSimage_id }}"
    region: "{{ AWSregion }}"
#    zone: "{{ AWSzone }}"
    vpc_subnet_id: "{{ AWSvpc_subnet_id[0] }}"
    wait: true
    exact_count: 1
    count_tag:
      Gluster: Client
      Subnet: "{{ AWSvpc_subnet_id[0] }}"
    instance_tags:
      Gluster: Client
      Name: GlusterClient
      Subnet: "{{ AWSvpc_subnet_id[0] }}"

- name: Provision Gluster Client in second subnet
  ec2:
    key_name: "{{ AWSkey_name }}"
    group_id: "{{ AWSgroup_id }}"
    instance_type: t2.micro
    assign_public_ip: yes
    image: "{{ AWSimage_id }}"
    region: "{{ AWSregion }}"
#    zone: "{{ AWSzone }}"
    vpc_subnet_id: "{{ AWSvpc_subnet_id[1] }}"
    wait: true
    exact_count: 1
    count_tag:
      Gluster: Client
      Subnet: "{{ AWSvpc_subnet_id[1] }}"
    instance_tags:
      Gluster: Client
      Subnet: "{{ AWSvpc_subnet_id[1] }}"
      Name: GlusterClient