--- # main task list for InstanceDeploy



- name: Provision Gluster Cluster
  ec2:
    key_name: "{{ AWSkey_name }}"
    group_id: "{{ AWSgroup_id }}"
    instance_type: t2.micro
    image: ami-49c9295f
    volumes: 
      - device_name: /dev/sdb
        delete_on_termination: true
        volume_type: gp2
        volume_size: 2
        snapshot: snap-04adac52ef92895ad
    region: "{{ AWSregion }}"
    zone: us-east-1b
    vpc_subnet_id: "{{ AWSvpc_subnet_id }}"
    wait: true
    exact_count: 2
    count_tag:
      Gluster: Cluster
    instance_tags:
      Gluster: Cluster
      Name: GlusterCluster


- name: Provision Gluster Client
  ec2:
    key_name: "{{ AWSkey_name }}"
    group_id: "{{ AWSgroup_id }}"
    instance_type: t2.micro
    image: ami-49c9295f
    region: "{{ AWSregion }}"
    zone: "{{ AWSzone }}"
    vpc_subnet_id: "{{ AWSvpc_subnet_id }}"
    wait: true
    exact_count: 0
    count_tag:
      Gluster: Client
    instance_tags:
      Gluster: Client
      Name: GlusterClient