--- # this is to try to get gluster clustering

- hosts: tag_Gluster_Cluster
  become: yes
  become_method: sudo
  gather_facts: true 
  tasks:
    - name: verify Gluster volume started
      gluster_volume:
        state: started
        name: test1
        bricks: /export/xvdb1/brick1
        cluster: 
          - tag_Gluster_Cluster
        replicas: 2
      run_once: yes